DATASET:
  NAME : 'tum'
  KITTI: 
    DATA_PATH: './seq/2011_09_30_drive_0018_sync/image_02/data/'
    TIMESTAMPS : './seq/2011_09_30_drive_0018_sync/timestamps.txt'
    ODOM_PATH : './seq/2011_09_30_drive_0018_sync/05.txt'
    MAX_VEL: 1.5
    TRANSFORMS:
      Velo2cam : [[7.533745e-03, -9.999714e-01, -6.166020e-04, -4.069766e-03], 
                  [1.480249e-02,  7.280733e-04, -9.998902e-01, -7.631618e-02], 
                  [9.998621e-01,  7.523790e-03,  1.480755e-02, -2.717806e-01],
                  [0.0, 0.0, 0.0, 1.0]]

    CAMERA:
      focal_length_x   : 7.215377e+02 
      focal_length_y   : 7.215377e+02
      optical_center_x : 6.095593e+02
      optical_center_y : 1.728540e+02

  TUM: 
    RGB_PATH:    './seq/rgbd_dataset_freiburg3_walking_rpy/rgb'
    DEPTH_PATH : './seq/rgbd_dataset_freiburg3_walking_rpy/depth'
    ODOM_PATH :  './seq/rgbd_dataset_freiburg3_walking_rpy/groundtruth'
    MAX_VEL: 0.1
    DEPTH_FACTOR: 5000.0

    CAMERA:
      focal_length_x   : 535.4 
      focal_length_y   : 539.2
      optical_center_x : 320.1
      optical_center_y : 247.6

CLASSES:
  ALL : [   'person', 'bicycle', 'car', 'motorcycle',
            'airplane', 'bus', 'train', 'truck', 'boat',
            'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 
            'bird', 'cat', 'dog', 'horse', 'sheep', 
            'cow', 'elephant', 'bear', 'zebra', 'giraffe', 
            'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 
            'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 
            'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
            'bottle', 'wine glass', 'cup', 'fork', 'knife', 
            'spoon', 'bowl', 'banana', 'apple', 'sandwich', 
            'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
            'donut', 'cake', 'chair', 'couch', 'potted plant', 
            'bed', 'dining table', 'toilet', 'tv', 'laptop',
            'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 
            'oven', 'toaster', 'sink', 'refrigerator', 'book',
            'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 
            'toothbrush']
  RIGID : ['bicycle', 'car', 'bus', 'train', 'truck', 'bench', 'handbag',
           'suitcase', 'chair', 'couch', 'dining table', 'tv', 'laptop', 
           'cell phone', 'microwave','oven', 'toaster', 'refrigerator', 
           'book', 'clock', 'vase', 'scissors']
  NON_RIGID: ['person', 'bird', 'cat', 'dog', 'horse']

SAVE_MASK : True
USE_CUDA : True
MASK_POINTS: 20.0
MAX_DEPTH: 50.0
MAX_IOU: 0.85
PUBLISH_ROS_TOPIC: True
ROS_TOPIC: "/segmentation_mask"